name: abi2fastq-env
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- biopython
- mmtf-python
- certifi
- click
- coverage
- flake8
- freetype
- jbig
- jpeg
- libpng
- libtiff
- mccabe
- mkl
- msgpack-python
- numpy
- olefile
- openssl
- pillow
- pip
- py
- pycodestyle
- pyflakes
- pytest
- python
- readline
- reportlab
- setuptools
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - abi2fastq

